### ISSUE TITLE
Pre-compiled for ES5

### ISSUE THREAD

**Issue by wramp** [sindresorhus/round-to#11]
Im trying to use this package with my React app, but it will get build fails.

Failed to minify the code from this file:
        ./node_modules/round-to/index.js:17

Could this package be pre-compiled to ES5?

Thanks

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
