### ISSUE TITLE
Performance of roundTo.down

### ISSUE THREAD

**Issue by edolganov** [sindresorhus/round-to#12]
Hi!
I checked **roundTo.down** method and the alternative one:
```
var delta = Math.pow(10, precision)
var result = Math.floor(input * delta) / delta;
```

Example: 
```
>> Math.floor(110.30115528834406 * 100000000) / 100000000
<< 110.30115528
```

I used both implementations 1,000,000 times. 
Check out results:
:-1: **roundTo.down** -  1.396 sec
:+1: **alternative** - 0.017sec  

Hope it will help you to improve a roundTo.down performance :smiley:

**Comment by sindresorhus** [comment]
From what I can remember, it has to do with floating-point precision.

This is what Lodash is doing too: https://github.com/lodash/lodash/blob/6bdb8a2f75fa61473f2a93e4d65d0a0ccdea0c86/.internal/createRound.js
