### ISSUE TITLE
Template strings introduced in version 3

### ISSUE THREAD

**Issue by mjkstudios** [sindresorhus/round-to#13]
The bundler for my project has started complaining about the template strings that were introduced in version 3. Specifically, the UglifyJs plugin that is packaged with Webpack 3 is throwing this error:

```
Unexpected character '`'
```

Can the code be transpiled to ES5?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
