### ISSUE TITLE
Error round(0.0995, 3)

### ISSUE THREAD

**Issue by Magomogo** [sindresorhus/round-to#3]
expected: 0.100
got: 0.099

**Comment by sindresorhus** [comment]
This is what I get:

```js
console.log(roundTo(0.0995, 3));
//=> 0.1
```

**Comment by Magomogo** [comment]
Sorry, my fault, I did 
    var num = 0.597/6 // 0.0995
    roundTo(num, 3) // 0.099

**Comment by Magomogo** [comment]
It's not a problem of the component. But I'm stuck, how to make javascript to calculate this right?

**Comment by sindresorhus** [comment]
http://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript
