### ISSUE TITLE
rounding extremely big or small numbers

### ISSUE THREAD

**Issue by leoaretakis** [sindresorhus/round-to#5]
Hi Guys, 

there is a problem with the code when the number is very big or very small, and their toString value returns a number in scientific format (string containing "e").
I can try to fix it and create a pull request, if you don't mind.

Cheers
Leo

**Comment by sindresorhus** [comment]
Sure, that would be lovely 😀

**Comment by leoaretakis** [comment]
Cannot be done, you guys made it allow negative precision.
In my case I had to use bignumber.js
Thanks anyway :)
