### ISSUE TITLE
Rounding 5 with negative numbers 

### ISSUE THREAD

**Issue by Railslide** [sindresorhus/round-to#6]
When rounding negative numbers, `5` behaves differently from what I would expect / how it works in other programming languages.

```
roundTo(0.375, 2);
// 0.38

roundTo(-0.375, 2);
// -0.37 (I was expecting -0.38)
```

Not sure if that's by design or not.

**Comment by sindresorhus** [comment]
Yeah, that seems like a bug.

**Comment by SamVerschueren** [comment]
What is the expected result of the following expressions?

```js
roundTo.up(-0.375, 2);
roundTo.down(-0.375, 2);
```

Does `up` means more negative and thus `-0.38` and down more positive and thus `-0.37` or the other way around?

**Comment by Railslide** [comment]
I would expect

```
roundTo.up(-0.375, 2);
// -0.37
roundTo.down(-0.375, 2);
// -0.38
```

Actually, it looks like `Math.round` is the culprit, since:

```
Math.round(-0.5);
// 0
Mathr.round(0.5):
// 1
```

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/round-to/pull/8.
