### ISSUE TITLE
const throws error in older browsers

### ISSUE THREAD

**Issue by giannif** [sindresorhus/round-to#9]
`const` isn't supported in [older browsers](https://caniuse.com/#search=const), causing our site to crash when it loads the `round-to` module. `node_modules` aren't meant to be transpiled, so you can't use `const` if you want to support all browsers

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
